(autoload 'multi-term                           "multi-term" "" t)
(autoload 'multi-term-next                      "multi-term" "" t)
(autoload 'multi-term-prev                      "multi-term" "" t)
(autoload 'multi-term-dedicated-open            "multi-term" "" t)
(autoload 'multi-term-dedicated-close           "multi-term" "" t)
(autoload 'multi-term-dedicated-toggle          "multi-term" "" t)
(autoload 'multi-term-dedicated-select          "multi-term" "" t)
(autoload 'term-send-backward-kill-word         "multi-term" "" t)
(autoload 'term-send-forward-kill-word          "multi-term" "" t)
(autoload 'term-send-backward-word              "multi-term" "" t)
(autoload 'term-send-forward-word               "multi-term" "" t)
(autoload 'term-send-reverse-search-history     "multi-term" "" t)
(autoload 'multi-term-window-dedicated-only-one-p "multi-term" "" t)
(provide 'multi-term-epkg-install)
